//@version=2
strategy("4H CCI Strategy 1.5", overlay=true)
length = input( 11 )
overSold = input( -100 )
overBought = input( +100 )
price1 = high
price2 = low
ucci = cci(price1, length)
dcci = cci(price2, length)
tp = (atr(66))*600000
sl = (atr(66))*300000
trade_size = (1000/sl)*100000
strategy.entry("CCILE", strategy.long, comment="CCILE",qty=trade_size, when=crossover(dcci, overSold))
strategy.exit(id="CCILE", profit = tp, loss = sl)
strategy.entry("CCISE", strategy.short, comment="CCISE",qty=trade_size,when=crossunder(ucci, overBought))
strategy.exit(id="CCISE", profit = tp, loss = sl)
//plot(strategy.equity, title="equity", color=red, linewidth=2, style=areabr)
