study(title="WMA Short term Bands", shorttitle="WMASTB", overlay=true)
source = close
length = input(56, minval=1, title = "WMA Length")
atrlen = input(100, minval=1, title = "ATR Length")
mult1 = 2
mult2 = 3
ma = wma(source, length)
range =  tr
rangema = wma(range, atrlen)

up1 = ma + rangema * mult1
up2 = ma + rangema * mult2

dn1 = ma - rangema * mult1
dn2 = ma - rangema * mult2

color1 = red
color2 = red

u4 = plot(up1, color = color1)
u8 = plot(up2, color = color2)

d4 = plot(dn1, color = color1)
d8 = plot(dn2, color = color2)
